# Generated by Django 5.2 on 2025-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('MERCHANT', 'Merchant (Shop Owner)'), ('CUSTOMER', 'Customer')], max_length=20),
        ),
    ]
